version: '3.1'

services:


  db:
    image: mysql
    env_file: .env.dev
    networks:
      - phototankswarm
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - phototankswarm

  redis:
    image: redis
    networks:
      - phototankswarm

  api:
    tty: true
    stdin_open: true
    image: pt-rails:v15
    env_file: .env.dev
    networks:
      - phototankswarm
    entrypoint: ./bin/rails.sh
    volumes:
      - /Users/mhe/Pictures/docker/phototank:/media/phototank
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis


  resque:
    tty: true
    stdin_open: true
    entrypoint: ./bin/resque.sh
    image: pt-rails:v15
    volumes:
      - /Users/mhe/Pictures/docker/phototank:/media/phototank
      - ./:/usr/src/app
    networks:
      - phototankswarm
    links:
      - redis
    env_file: .env.dev

  portainer:
    image:
      portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - phototankswarm

networks:
  phototankswarm:
