development:
  environment: development
  host: redis
  port: 6379
  db: 6


test:
  environment: test
  host: redis
  port: 6379
  db: 6

production:
  environment: production
  host: 192.168.2.201
  port: 6379
  db: 6
